name: azimuth-timing
channels:
 - conda-forge
dependencies:
 - python
 - jupyter
 - rasterio
 - numpy
 - matplotlib
 - pandas
 - isce3
 - asf_search
 - raider
 - xarray
 - netcdf4
 - rioxarray
 - hyp3lib>=1.7
 - flake8-blind-except
 - flake8-builtins
 - flake8-import-order
 - pytest
